# Generated by Django 3.0.4 on 2020-04-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200411_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
