# Generated by Django 3.0.4 on 2020-04-24 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
    ]
