# Generated by Django 3.0.4 on 2020-04-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
