# Generated by Django 3.0.4 on 2020-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0004_auto_20200413_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
