# Generated by Django 3.0.4 on 2020-04-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
