# Generated by Django 3.0.4 on 2020-04-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0009_auto_20200413_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='instructions',
        ),
    ]
