# Generated by Django 3.0.4 on 2020-04-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0010_remove_order_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_at',
            new_name='timing',
        ),
    ]
