# Generated by Django 3.0.4 on 2020-04-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0014_auto_20200424_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timing',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
