# Generated by Django 3.0.4 on 2020-04-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0015_auto_20200424_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timing',
        ),
    ]
