# Generated by Django 3.0.4 on 2020-04-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0016_remove_order_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
