# Generated by Django 3.0.4 on 2020-04-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0017_auto_20200424_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default='2020-04-24', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, default='09:47 PM', null=True),
        ),
    ]
