# Generated by Django 3.0.4 on 2020-04-25 03:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0018_auto_20200424_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 25, 3, 51, 46, 28251, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2020, 4, 25, 3, 51, 46, 28289, tzinfo=utc), null=True),
        ),
    ]
