# Generated by Django 3.0.4 on 2020-04-25 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0019_auto_20200424_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 24), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, default=datetime.time(21, 57, 2, 173208), null=True),
        ),
    ]
