# Generated by Django 3.0.4 on 2020-04-25 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0023_auto_20200424_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
