# Generated by Django 3.0.4 on 2020-04-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0027_auto_20200428_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='price',
        ),
    ]
