# Generated by Django 3.0.4 on 2020-05-05 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webplatform', '0032_auto_20200504_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted_user@example.com'), to='webplatform.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted_user@example.com'), to=settings.AUTH_USER_MODEL),
        ),
    ]
