# Generated by Django 3.0.4 on 2020-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0034_auto_20200505_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='portion_increment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
