# Generated by Django 3.0.4 on 2020-05-07 23:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0035_item_portion_increment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeliverydetail',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 7, 23, 42, 22, 983020, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 7, 23, 42, 23, 143755, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdeliverydetail',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
