# Generated by Django 3.0.4 on 2020-05-08 00:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0036_auto_20200507_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 0, 9, 52, 57016, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 8, 0, 9, 52, 107742, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userdeliverydetail',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='subscribe weekly'),
        ),
    ]
