# Generated by Django 3.0.4 on 2020-05-12 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webplatform', '0037_auto_20200507_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feel_if_no_longer', models.CharField(choices=[('VD', 'Very disappointed'), ('SD', 'Somewhat disappointed'), ('ND', 'Not disappointed')], max_length=2, verbose_name='How would you feel if you could no longer use Meal Hippo?')),
                ('type_of_people', models.TextField(verbose_name='What type of people do you think would most benefit from Meal Hippo?')),
                ('main_benefit', models.TextField(verbose_name='What is the main benefit you receive from Meal Hippo?')),
                ('how_to_improve', models.TextField(verbose_name='How can we improve Meal Hippo for you?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
