# Generated by Django 3.0.4 on 2020-05-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0038_auto_20200511_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feel_if_no_longer',
            field=models.CharField(choices=[('VD', 'Very disappointed'), ('SD', 'Somewhat disappointed'), ('ND', 'Not disappointed')], default=None, max_length=2, verbose_name='How would you feel if you could no longer use Meal Hippo?'),
        ),
    ]
