# Generated by Django 3.0.4 on 2020-05-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0039_auto_20200514_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
