# Generated by Django 3.0.4 on 2020-05-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0040_auto_20200514_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='carbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
