# Generated by Django 3.0.4 on 2020-05-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0041_auto_20200516_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
