# Generated by Django 3.0.4 on 2020-05-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0043_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeliverydetail',
            name='free_delivery',
            field=models.BooleanField(default=True),
        ),
    ]
