# Generated by Django 3.0.4 on 2020-06-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0044_userdeliverydetail_free_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
