# Generated by Django 3.0.4 on 2020-06-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0045_item_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
