# Generated by Django 3.0.4 on 2020-06-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0046_auto_20200602_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='calories',
        ),
    ]
