# Generated by Django 3.0.4 on 2020-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0047_remove_item_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
