# Generated by Django 3.0.4 on 2020-08-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0048_item_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_be_delivered',
            field=models.BooleanField(default=True),
        ),
    ]
