# Generated by Django 3.0.4 on 2020-08-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0049_order_to_be_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
