# Generated by Django 3.0.4 on 2020-08-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0050_orderitem_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
