# Generated by Django 3.0.4 on 2020-08-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0051_item_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='portion_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
