# Generated by Django 3.0.4 on 2020-08-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0052_item_portion_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
