# Generated by Django 3.0.4 on 2020-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0053_order_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='comments',
            new_name='notes',
        ),
        migrations.AlterField(
            model_name='userdeliverydetail',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery instructions'),
        ),
    ]
