# Generated by Django 3.0.4 on 2020-09-20 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webplatform', '0054_auto_20200818_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Order notes'),
        ),
        migrations.CreateModel(
            name='UserSupplierInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_supplier', models.BooleanField()),
                ('first_name', models.CharField(max_length=56, verbose_name='Your first name')),
                ('last_name', models.CharField(max_length=56, verbose_name='Your last name')),
                ('company_name', models.CharField(max_length=56)),
                ('company_address', models.TextField()),
                ('agree_to_terms_conditions', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
