# Generated by Django 3.0.4 on 2020-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0057_auto_20200920_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='end_time_h',
            field=models.IntegerField(blank=True, choices=[('01:', 1), ('02:', 2), ('03:', 3), ('04:', 4), ('05:', 5), ('06:', 6), ('07:', 7), ('08:', 8), ('09:', 9), ('10:', 10), ('11:', 11), ('12:', 12), ('13:', 13), ('14:', 14), ('15:', 15), ('16:', 16), ('17:', 17), ('18:', 18), ('19:', 19), ('20:', 20), ('21:', 21), ('22:', 22), ('23:', 23)], null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='end_time_m',
            field=models.IntegerField(blank=True, choices=[(':00', 0), (':30', 30)], null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='start_time_h',
            field=models.IntegerField(blank=True, choices=[('01:', 1), ('02:', 2), ('03:', 3), ('04:', 4), ('05:', 5), ('06:', 6), ('07:', 7), ('08:', 8), ('09:', 9), ('10:', 10), ('11:', 11), ('12:', 12), ('13:', 13), ('14:', 14), ('15:', 15), ('16:', 16), ('17:', 17), ('18:', 18), ('19:', 19), ('20:', 20), ('21:', 21), ('22:', 22), ('23:', 23)], null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='start_time_m',
            field=models.IntegerField(blank=True, choices=[(':00', 0), (':30', 30)], null=True),
        ),
        migrations.AlterField(
            model_name='usersupplierinfo',
            name='agree_to_terms_conditions',
            field=models.BooleanField(default=False, help_text='<a href="/static/webplatform/Terms-and-Conditions-for-Services-Caterers.pdf" target="_blank">General Terms and Conditions for Services &ndash; Caterers</a>', verbose_name='I agree to the General Terms and Conditions for Services &ndash; Caterers&mdash;as amended from time to time.'),
        ),
    ]
