# Generated by Django 3.0.4 on 2020-09-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0059_auto_20200926_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='supplier',
            name='end_time_h',
            field=models.IntegerField(blank=True, choices=[(0, '00:'), (1, '01:'), (2, '02:'), (3, '03:'), (4, '04:'), (5, '05:'), (6, '06:'), (7, '07:'), (8, '08:'), (9, '09:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:'), (14, '14:'), (15, '15:'), (16, '16:'), (17, '17:'), (18, '18:'), (19, '19:'), (20, '20:'), (21, '21:'), (22, '22:'), (23, '23:')], null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='start_time_h',
            field=models.IntegerField(blank=True, choices=[(0, '00:'), (1, '01:'), (2, '02:'), (3, '03:'), (4, '04:'), (5, '05:'), (6, '06:'), (7, '07:'), (8, '08:'), (9, '09:'), (10, '10:'), (11, '11:'), (12, '12:'), (13, '13:'), (14, '14:'), (15, '15:'), (16, '16:'), (17, '17:'), (18, '18:'), (19, '19:'), (20, '20:'), (21, '21:'), (22, '22:'), (23, '23:')], null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='date_range',
            field=models.ManyToManyField(to='webplatform.Day'),
        ),
    ]
