# Generated by Django 3.0.4 on 2020-09-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0060_auto_20200926_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
