# Generated by Django 3.0.4 on 2020-09-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0062_auto_20200926_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='date_range',
            new_name='day_range',
        ),
    ]
