# Generated by Django 3.0.4 on 2020-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0063_auto_20200926_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
