# Generated by Django 3.0.4 on 2020-10-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0066_auto_20201017_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='is_on_meal_hippo',
            field=models.BooleanField(default=False),
        ),
    ]
