# Generated by Django 3.0.4 on 2020-10-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0068_listitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='business_name_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
