# Generated by Django 3.0.4 on 2020-10-18 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webplatform', '0069_supplier_business_name_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='business_name_slug',
        ),
    ]
